version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  commit-message:
    prefix: '[bot]'
  labels:
    - "dependencies"
  open-pull-requests-limit: 0
  versioning-strategy: lockfile-only
