import { TableRow, TableColumn } from 'suomifi-ui-components';

const columns: TableColumn[] = [
  {
    key: 'firstName',
    labelText: 'Etunimi',
    sortable: true,
  },
  {
    key: 'lastName',
    labelText: 'Sukunimi',
    sortable: true,
  },
  {
    key: 'hours_worked',
    labelText: 'Työtunnit',
    textAlign: 'right',
    sortable: true,
    sortIcon: 'generic',
  },
  {
    key: 'country',
    labelText: 'Kotimaa',
    className: 'testing-class',
  },
];

const fullData: TableRow<readonly TableColumn[]>[] = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Doe',
    hours_worked: 125,
    country: 'UK',
  },
  {
    id: '2',
    firstName: 'Jane',
    lastName: 'Doe',
    hours_worked: 150,
    country: 'Norja',
  },
  {
    id: '3',
    firstName: 'Bruce',
    lastName: 'Willis',
    hours_worked: 10,
    country: 'Yhdysvallat',
  },
  {
    id: '4',
    firstName: 'Harriet',
    lastName: 'Ackermann',
    hours_worked: '',
    country: 'Saksa',
  },
  {
    id: '5',
    firstName: 'Alexander',
    lastName: 'Stubb',
    hours_worked: 2543,
    country: 'Suomi',
  },
  {
    id: '6',
    firstName: 'Emily',
    lastName: 'Clark',
    hours_worked: 200,
    country: 'Kanada',
  },
  {
    id: '7',
    firstName: 'Michael',
    lastName: 'Smith',
    hours_worked: 300,
    country: 'Australia',
  },
  {
    id: '8',
    firstName: 'Sarah',
    lastName: 'Johnson',
    hours_worked: 400,
    country: 'Uusi-Seelanti',
  },
  {
    id: '9',
    firstName: 'David',
    lastName: 'Brown',
    hours_worked: 500,
    country: 'Irlanti',
  },
  {
    id: '10',
    firstName: 'Laura',
    lastName: 'Wilson',
    hours_worked: 600,
    country: 'Ruotsi',
  },
  {
    id: '11',
    firstName: 'James',
    lastName: 'Taylor',
    hours_worked: 700,
    country: 'Tanska',
  },
  {
    id: '12',
    firstName: 'Olivia',
    lastName: 'Anderson',
    hours_worked: 800,
    country: 'Alankomaat',
  },
  {
    id: '13',
    firstName: 'Daniel',
    lastName: 'Thomas',
    hours_worked: 900,
    country: 'Belgia',
  },
  {
    id: '14',
    firstName: 'Sophia',
    lastName: 'Martinez',
    hours_worked: 1000,
    country: 'Espanja',
  },
  {
    id: '15',
    firstName: 'Matthew',
    lastName: 'Garcia',
    hours_worked: 1100,
    country: 'Portugali',
  },
  {
    id: '16',
    firstName: 'Isabella',
    lastName: 'Robinson',
    hours_worked: 1200,
    country: 'Italia',
  },
  {
    id: '17',
    firstName: 'Ethan',
    lastName: 'Walker',
    hours_worked: 1300,
    country: 'Ranska',
  },
  {
    id: '18',
    firstName: 'Mia',
    lastName: 'Hall',
    hours_worked: 1400,
    country: 'Sveitsi',
  },
  {
    id: '19',
    firstName: 'Alexander',
    lastName: 'Young',
    hours_worked: 1500,
    country: 'Itävalta',
  },
  {
    id: '20',
    firstName: 'Ava',
    lastName: 'Hernandez',
    hours_worked: 1600,
    country: 'Kreikka',
  },
  {
    id: '21',
    firstName: 'William',
    lastName: 'King',
    hours_worked: 1700,
    country: 'Puola',
  },
  {
    id: '22',
    firstName: 'Emily',
    lastName: 'Lopez',
    hours_worked: 1800,
    country: 'Unkari',
  },
  {
    id: '23',
    firstName: 'Benjamin',
    lastName: 'Hill',
    hours_worked: 1900,
    country: 'Tšekki',
  },
  {
    id: '24',
    firstName: 'Charlotte',
    lastName: 'Scott',
    hours_worked: 2000,
    country: 'Slovakia',
  },
  {
    id: '25',
    firstName: 'Lucas',
    lastName: 'Green',
    hours_worked: 2100,
    country: 'Slovenia',
  },
  {
    id: '26',
    firstName: 'Amelia',
    lastName: 'Adams',
    hours_worked: 2200,
    country: 'Kroatia',
  },
  {
    id: '27',
    firstName: 'Henry',
    lastName: 'Baker',
    hours_worked: 2300,
    country: 'Bulgaria',
  },
  {
    id: '28',
    firstName: 'Evelyn',
    lastName: 'Gonzalez',
    hours_worked: 2400,
    country: 'Romania',
  },
  {
    id: '29',
    firstName: 'Jack',
    lastName: 'Nelson',
    hours_worked: 2500,
    country: 'Serbia',
  },
  {
    id: '30',
    firstName: 'Abigail',
    lastName: 'Carter',
    hours_worked: 2600,
    country: 'Montenegro',
  },
  {
    id: '31',
    firstName: 'Samuel',
    lastName: 'Mitchell',
    hours_worked: 2700,
    country: 'Makedonia',
  },
  {
    id: '32',
    firstName: 'Sofia',
    lastName: 'Perez',
    hours_worked: 2800,
    country: 'Bosnia ja Hertsegovina',
  },
  {
    id: '33',
    firstName: 'David',
    lastName: 'Roberts',
    hours_worked: 2900,
    country: 'Albania',
  },
  {
    id: '34',
    firstName: 'Ella',
    lastName: 'Turner',
    hours_worked: 3000,
    country: 'Kosovo',
  },
  {
    id: '35',
    firstName: 'Joseph',
    lastName: 'Phillips',
    hours_worked: 3100,
    country: 'Viro',
  },
  {
    id: '36',
    firstName: 'Grace',
    lastName: 'Campbell',
    hours_worked: 3200,
    country: 'Latvia',
  },
  {
    id: '37',
    firstName: 'Andrew',
    lastName: 'Parker',
    hours_worked: 3300,
    country: 'Liettua',
  },
  {
    id: '38',
    firstName: 'Chloe',
    lastName: 'Evans',
    hours_worked: 3400,
    country: 'Valko-Venäjä',
  },
  {
    id: '39',
    firstName: 'Daniel',
    lastName: 'Edwards',
    hours_worked: 3500,
    country: 'Ukraina',
  },
  {
    id: '40',
    firstName: 'Victoria',
    lastName: 'Collins',
    hours_worked: 3600,
    country: 'Moldova',
  },
  {
    id: '41',
    firstName: 'James',
    lastName: 'Stewart',
    hours_worked: 3700,
    country: 'Georgia',
  },
  {
    id: '42',
    firstName: 'Avery',
    lastName: 'Sanchez',
    hours_worked: 3800,
    country: 'Armenia',
  },
  {
    id: '43',
    firstName: 'Christopher',
    lastName: 'Morris',
    hours_worked: 3900,
    country: 'Azerbaidžan',
  },
  {
    id: '44',
    firstName: 'Madison',
    lastName: 'Rogers',
    hours_worked: 4000,
    country: 'Kazakhstan',
  },
  {
    id: '45',
    firstName: 'Joshua',
    lastName: 'Reed',
    hours_worked: 4100,
    country: 'Uzbekistan',
  },
  {
    id: '46',
    firstName: 'Scarlett',
    lastName: 'Cook',
    hours_worked: 4200,
    country: 'Turkmenistan',
  },
  {
    id: '47',
    firstName: 'Anthony',
    lastName: 'Morgan',
    hours_worked: 4300,
    country: 'Kirgisia',
  },
  {
    id: '48',
    firstName: 'Aria',
    lastName: 'Bell',
    hours_worked: 4400,
    country: 'Tadžikistan',
  },
  {
    id: '49',
    firstName: 'Thomas',
    lastName: 'Murphy',
    hours_worked: 4500,
    country: 'Afganistan',
  },
  {
    id: '50',
    firstName: 'Lily',
    lastName: 'Bailey',
    hours_worked: 4600,
    country: 'Pakistan',
  },
  {
    id: '51',
    firstName: 'Ryan',
    lastName: 'Rivera',
    hours_worked: 4700,
    country: 'Intia',
  },
  {
    id: '52',
    firstName: 'Zoe',
    lastName: 'Cooper',
    hours_worked: 4800,
    country: 'Nepal',
  },
  {
    id: '53',
    firstName: 'Nathan',
    lastName: 'Richardson',
    hours_worked: 4900,
    country: 'Bhutan',
  },
  {
    id: '54',
    firstName: 'Hannah',
    lastName: 'Cox',
    hours_worked: 5000,
    country: 'Bangladesh',
  },
  {
    id: '55',
    firstName: 'Isaac',
    lastName: 'Ward',
    hours_worked: 5100,
    country: 'Sri Lanka',
  },
  {
    id: '56',
    firstName: 'Aubrey',
    lastName: 'Torres',
    hours_worked: 5200,
    country: 'Malediivit',
  },
  {
    id: '57',
    firstName: 'Gabriel',
    lastName: 'Peterson',
    hours_worked: 5300,
    country: 'Myanmar',
  },
  {
    id: '58',
    firstName: 'Lillian',
    lastName: 'Gray',
    hours_worked: 5400,
    country: 'Thaimaa',
  },
  {
    id: '59',
    firstName: 'Owen',
    lastName: 'Ramirez',
    hours_worked: 5500,
    country: 'Laos',
  },
  {
    id: '60',
    firstName: 'Addison',
    lastName: 'James',
    hours_worked: 5600,
    country: 'Kambodža',
  },
  {
    id: '61',
    firstName: 'Wyatt',
    lastName: 'Watson',
    hours_worked: 5700,
    country: 'Vietnam',
  },
  {
    id: '62',
    firstName: 'Layla',
    lastName: 'Brooks',
    hours_worked: 5800,
    country: 'Malesia',
  },
  {
    id: '63',
    firstName: 'Sebastian',
    lastName: 'Kelly',
    hours_worked: 5900,
    country: 'Singapore',
  },
  {
    id: '64',
    firstName: 'Avery',
    lastName: 'Sanders',
    hours_worked: 6000,
    country: 'Indonesia',
  },
  {
    id: '65',
    firstName: 'Carter',
    lastName: 'Price',
    hours_worked: 6100,
    country: 'Filippiinit',
  },
  {
    id: '66',
    firstName: 'Julian',
    lastName: 'Bennett',
    hours_worked: 6200,
    country: 'Brunei',
  },
  {
    id: '67',
    firstName: 'Nora',
    lastName: 'Wood',
    hours_worked: 6300,
    country: 'Japani',
  },
  {
    id: '68',
    firstName: 'Christian',
    lastName: 'Barnes',
    hours_worked: 6400,
    country: 'Etelä-Korea',
  },
  {
    id: '69',
    firstName: 'Zoey',
    lastName: 'Ross',
    hours_worked: 6500,
    country: 'Pohjois-Korea',
  },
  {
    id: '70',
    firstName: 'Hunter',
    lastName: 'Henderson',
    hours_worked: 6600,
    country: 'Kiina',
  },
  {
    id: '71',
    firstName: 'Leah',
    lastName: 'Coleman',
    hours_worked: 6700,
    country: 'Mongolia',
  },
  {
    id: '72',
    firstName: 'Jonathan',
    lastName: 'Jenkins',
    hours_worked: 6800,
    country: 'Venäjä',
  },
  {
    id: '73',
    firstName: 'Hazel',
    lastName: 'Perry',
    hours_worked: 6900,
    country: 'Kazakhstan',
  },
  {
    id: '74',
    firstName: 'Aaron',
    lastName: 'Powell',
    hours_worked: 7000,
    country: 'Uzbekistan',
  },
  {
    id: '75',
    firstName: 'Ellie',
    lastName: 'Long',
    hours_worked: 7100,
    country: 'Turkmenistan',
  },
  {
    id: '76',
    firstName: 'Lincoln',
    lastName: 'Patterson',
    hours_worked: 7200,
    country: 'Kirgisia',
  },
  {
    id: '77',
    firstName: 'Paisley',
    lastName: 'Hughes',
    hours_worked: 7300,
    country: 'Tadžikistan',
  },
  {
    id: '78',
    firstName: 'Henry',
    lastName: 'Flores',
    hours_worked: 7400,
    country: 'Afganistan',
  },
  {
    id: '79',
    firstName: 'Aurora',
    lastName: 'Washington',
    hours_worked: 7500,
    country: 'Pakistan',
  },
  {
    id: '80',
    firstName: 'Eli',
    lastName: 'Butler',
    hours_worked: 7600,
    country: 'Intia',
  },
];

fullData.map((item) => ({
  ...item,
  rowSelectionCheckBoxLabel: `Valitse rivi ${item.firstName} ${item.lastName}`,
}));

const showOnPageOptions = [
  { name: '10', key: '10' },
  { name: '20', key: '20' },
  { name: '30', key: '30' },
  { name: '40', key: '40' },
  { name: '50', key: '50' },
];

const filterByWorkHoursOptions = [
  { name: 'Kaikki', key: 'all' },
  { name: '< 100', key: '100' },
  { name: '< 500', key: '500' },
  { name: '< 1000', key: '1000' },
  { name: '< 3000', key: '3000' },
  { name: '< 5000', key: '5000' },
];

export { columns, fullData, showOnPageOptions, filterByWorkHoursOptions };
