version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    version_requirement_updates: 'off'
    target_branch: 'feature/dependabot-config'
    default_reviewers: ['aappoalander']
    allowed_updates:
      - match:
          dependency_type: 'indirect'
          update_type: 'all'
